# Generated by Django 3.0.4 on 2020-04-13 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='body',
        ),
    ]
