# Generated by Django 3.0.4 on 2020-04-13 21:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_remove_entry_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Tastypie',
        ),
    ]
